module.exports = Object.freeze({
    TRANSFER: 'TRANSFER',
    RECEIVE_MONEY:'RECEIVEMONEY',
    WITHDRAW: 'WITHDRAW',
    DEPOSIT: 'DEPOSIT',
    STAKE_TRANSFER: 'STAKE_TRANSFER',
    STAKE_RECEIVE: 'STAKE_RECEIVE',
});